
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package CUP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 24;
  public static final int STRING_LITERAL = 10;
  public static final int OPEN_PAREN = 17;
  public static final int POWER = 26;
  public static final int INCREMENT = 27;
  public static final int CHAR = 5;
  public static final int CHAR_LITERAL = 9;
  public static final int CASE = 43;
  public static final int NOT_EQUAL = 34;
  public static final int INTEGER = 2;
  public static final int FOR = 41;
  public static final int MINUS = 22;
  public static final int DECREMENT = 28;
  public static final int GREATER_THAN = 31;
  public static final int NOT = 37;
  public static final int AND = 35;
  public static final int CLOSE_PAREN = 18;
  public static final int OR = 36;
  public static final int COMMA = 50;
  public static final int BOOL = 4;
  public static final int LESS_EQUAL = 30;
  public static final int OPEN_BLOCK = 13;
  public static final int PLUS = 21;
  public static final int MULTIPLY = 23;
  public static final int MAIN = 46;
  public static final int IF = 38;
  public static final int ASSIGN = 19;
  public static final int EOF = 0;
  public static final int RETURN = 52;
  public static final int EQUAL = 33;
  public static final int TRUE = 11;
  public static final int GREATER_EQUAL = 32;
  public static final int error = 1;
  public static final int MODULO = 25;
  public static final int CLOSE_BRACKET = 16;
  public static final int BREAK = 53;
  public static final int OPEN_BRACKET = 15;
  public static final int END_STATEMENT = 20;
  public static final int SWITCH = 42;
  public static final int COLON = 49;
  public static final int ELSE = 39;
  public static final int CLOSE_BLOCK = 14;
  public static final int READ = 48;
  public static final int WHILE = 40;
  public static final int DEFAULT = 44;
  public static final int FLOAT = 3;
  public static final int STRING = 6;
  public static final int FLOAT_LITERAL = 8;
  public static final int FALSE = 12;
  public static final int LESS_THAN = 29;
  public static final int BOOL_LITERAL = 51;
  public static final int PRINT = 47;
  public static final int INT_LITERAL = 7;
  public static final int IDENTIFIER = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "CHAR_LITERAL",
  "STRING_LITERAL",
  "TRUE",
  "FALSE",
  "OPEN_BLOCK",
  "CLOSE_BLOCK",
  "OPEN_BRACKET",
  "CLOSE_BRACKET",
  "OPEN_PAREN",
  "CLOSE_PAREN",
  "ASSIGN",
  "END_STATEMENT",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "MODULO",
  "POWER",
  "INCREMENT",
  "DECREMENT",
  "LESS_THAN",
  "LESS_EQUAL",
  "GREATER_THAN",
  "GREATER_EQUAL",
  "EQUAL",
  "NOT_EQUAL",
  "AND",
  "OR",
  "NOT",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "IDENTIFIER",
  "MAIN",
  "PRINT",
  "READ",
  "COLON",
  "COMMA",
  "BOOL_LITERAL",
  "RETURN",
  "BREAK"
  };
}

